name: Release

on:
  push:
    tags:
      - 'v*'          # only runs when you push a tag like v1.0.0, v1.2.3

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui-windows

      - name: Publish
        run: |
          $version = "${{ github.ref_name }}".TrimStart('v')  # strips the 'v' from v1.0.1
          dotnet publish ManicDigger.Maui/ManicDigger.Maui.csproj `
            -c Release -f net10.0-windows10.0.19041.0 -r win-x64 --self-contained true`
            /p:Version=$version

      - name: Zip output
        run: |
          Compress-Archive `
            -Path "ManicDigger.Maui/bin/Release/net10.0-windows10.0.19041.0/win-x64/publish/*" `
            -DestinationPath "ManicDigger-${{ github.ref_name }}-win-x64.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ManicDigger-${{ github.ref_name }}-win-x64.zip
          generate_release_notes: true  # auto-generates notes from commits since last tag
